rdkcentral/Lightning

- src/tree/Stage.mjs
- tests/textures/test.textures.js
Updated tests for texture throttling loader.
> Fixed initial texture twitching.

- src/tree/Texture.mjs
- tests/textures/test.textures.js
> Fix resize mode on texture change with existing source

- src/tree/Element.mjs
- src/tree/core/ElementCore.mjs
- tests/test.html
- tests/textures/test.text.js
> Fixed text texture stretching for dynamic functions.

- index.js
> Added importable index.js to package root.

- src/application/Component.mjs
> Hotfix for crash, when component outlives application.

- src/textures/TextTexture.mjs
Partially reverts d7592100fbf43b31f465eb8732b366acfc4bc617
> Revert text texture throttling which causes artifacts.

- src/textures/TextTexture.mjs
- src/textures/TextTextureRenderer.mjs
- tests/test.html
- tests/textures/test.text.js
> Added text overflow option

- src/lightning.mjs
- src/renderer/webgl/shaders/RoundedRectangleShader.mjs
> Added RoundedRectangle webgl shader

- src/textures/TextTextureRenderer.mjs
> Fixed text highlight offset calculation

- LICENSE
- NOTICE
BLDKCMF-7 Compliance Issues in Lightning, Fixed Review comments
> BLDKCMF-7 Compliance Issues in Lightning, Fixed Review comments

- src/platforms/browser/ImageWorker.mjs
> Fixed image worker's protocol resolving for relative urls.

- src/renderer/webgl/shaders/RoundedRectangleShader.mjs
- You can now add a stroke, strokeColor and fillColor
- Should be backwards compatible
> update round rectangle to newest version

- src/animation/Animation.mjs
Progress event should also receive the 1 value when the animation ends.
> Call event progress when the animation finishes

- src/renderer/webgl/WebGLShader.mjs
Fixes Outline, Pixelate and Dithering shaders.
Resolves #199
> Fixed bad value for vertexAttribOffset getter.

- src/animation/Animation.mjs
- src/application/Application.mjs
- src/application/StateMachine.mjs
- src/components/BloomComponent.mjs
- src/components/FastBlurComponent.mjs
- src/platforms/browser/WebPlatform.mjs
- src/renderer/Renderer.mjs
- src/renderer/webgl/WebGLShaderProgram.mjs
- src/renderer/webgl/shaders/CircularPushShader.mjs
- src/textures/HtmlTexture.mjs
- src/textures/TextTextureRenderer.mjs
- src/tree/Base.mjs
- src/tree/Element.mjs
- src/tree/Shader.mjs
- src/tree/Stage.mjs
- src/tree/StageUtils.mjs
- src/tree/TextureSource.mjs
> Cleaned up debug messages a little bit.

- src/application/Component.mjs
- src/application/StateMachine.mjs
> Remove ES6 const bindings that are not subject to transpilation.

- src/textures/TextTextureRenderer.mjs
Precision was not used to calculate letterSpacing
> TextTextureRenderer: added precision to letter spacing

- examples/shaders/magnifier/magnifier.html
- src/lightning.mjs
- src/renderer/webgl/shaders/MagnifierShader.mjs
> Added magnifier shader

- src/application/Component.mjs
> Allow binding objects to text property

- src/application/Application.mjs
- src/platforms/browser/WebPlatform.mjs
Adds hover, click & scroll functionality (intended for use with the LG Magic Remote but applicable to other pointers as it uses standard pointer events). Based on the POC described in #68.
To determine the hover/click target, the pointer is localised inside active candidate components. The item with the the highest z-index is assumed the target (id when z-indices are the same). The component tree is searched upwards for an assigned handler. Note, as the hover implementation makes use of the *mousemove* event, the hover handler is only called when the target component changes, removing excessive handler calls.
Both top-down and bottom-up handlers have been implemented for handling scroll wheel events as required.
> Pointer support

- devtools/lightning-inspect.js
- src/application/Application.mjs
> Added 'focus' attribute to inspector, added focus log.

- src/tree/ObjectList.mjs
> Allow childList's insert methods to accept patch object.

- examples/mouse-pointer/basic-usage.html
- examples/mouse-pointer/scroll.html
- src/application/Application.mjs
- src/tree/Element.mjs
- fixed collision detection on rtt and clipping settings
- added collision flag for customisation
- added examples
> Better pointer support

- src/textures/TextTexture.mjs
- src/tree/Stage.mjs
> Added options for text sharpening.

- examples/text/advanced-renderer.html
- src/textures/TextTexture.mjs
- src/textures/TextTextureRendererAdvanced.mjs
- tests/textures/test.text.js
Adds `advancedRenderer` property to text texture, which enables new text renderer.
Supports:
- \<b> tag
- \<i> tag
- \<color> tag
- basic form of `wordBreak`
Usage:
```{text: {text: 'hello' ..., advancedRender: true, wordBreak: true}```
> Advanced text renderer

- examples/mouse-pointer/cursor.html
- src/application/Application.mjs
> Added css cursor support.

- devtools/lightning-inspect.js
- src/platforms/browser/WebPlatform.mjs
- src/tree/Utils.mjs
> Fixed regression on Ziggo platforms

- src/platforms/browser/WebPlatform.mjs
- src/tree/Stage.mjs
Hi @g-zachar looking to move the RAF usage along, did some testing and it seems to work great. However to mitigate risk I'd like to make it opt-in so the default behavior remains unchanged. 
Let me know if this would work for you.
> Enable RAF idle usage with stage option 'pauseRafLoopOnIdle'

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Added changelog, release notes and bumped version to 2.7.0
> Added changelog, release notes and bumped version to 2.7.0

- docs/TypeScript/Components/SubclassableComponents.md
Prompted by: https://forum.lightningjs.io/t/subclassable-components-typescript/546
> docs(TypeScript): Add example of basic subclassing

- src/application/Application.mjs
resolves https://github.com/rdkcentral/Lightning/issues/485
> Add pointer event bubble support

- src/tree/Element.mjs
> Fixed recurssion limit on txLoaded.

- CHANGELOG.md
- package-lock.json
- package.json
- Adds `onIdle` event when `pauseRafLoopOnIdle` is enabled (#541 , #542 )
> Release - v2.14.0

- src/flex/FlexTarget.mjs
- src/renderer/c2d/shaders/DefaultShader.mjs
At scale we found a few cases of runtime exceptions.
> Small robustness improvement

- package.json
- src/textures/TextTokenizer.test.ts
- src/textures/TextTokenizer.ts
The condition was reversed 🤦 
Added unit tests
> Fix ASCII detection
