- package.json
- rollup.config.js
This change will add version information at the top of Lightning bundle created by rollup:
```javascript
/**
* Lightning v1.0.6
*
* https://github.com/WebPlatformForEmbedded/Lightning
*/
```
> Add Lightning version to bundle

- devtools/lightning-inspect.js
- `_debugId` - Set custom id attribute for `div` . This will replace the auto incrementing number.
- `tabindex` - tabindex is required to send keypress events on non-input elements (div). This will be added when `get tabindexed()` returns true
These changes are added support automated tests (E.g. Cypress)
> Additional attributes for automation tests

- package-lock.json
- package.json
- rollup.config.js
* Update rollup to latest version
* Update es5 transpilation target to exclude more of modern features (object property shorthand, typeof operator, template literals)
> Update rollup and es5 config

- src/tools/Tools.mjs
This is to prevent the following error when trying to load SVG images from foreign origins (that provide proper CORS headers):
```
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.
```
> Add 'crossOrigin' attribute to SVG image element.

- src/textures/TextTextureRenderer.mjs
When line height is larger than font size, text should be positioned in the center rather than on the top.
Resolves #164
> Fixed text line height centering.

- src/textures/TextTexture.mjs
- src/textures/TextTextureRenderer.mjs
Reverts #192
* By default, text will be aligned to top (as was prior to 1.8.1)
* Aligning text to middle or bottom is now possible by specifying `verticalAlign` option for text texture, e.g.
```javascript
text: {text: "Hello", verticalAlign: 'middle', fontSize: 24},
```
Options for `verticalAlign` are:
* `'top'` (default),
* `'middle'`,
* `'bottom'`
> Added verticalAlign option for text texture

- src/tree/TextureSource.mjs
Fixes #16
The PS4 (and potentially other platforms) do not support WebGL and therefore `WebGLTexture` is undefined on the global `window` object.
RDK CLA has been signed.
> Add guard in TextureSource#_isNativeTexture for platforms that don't have WebGL support

- src/platforms/browser/ImageWorker.mjs
- src/platforms/browser/WebPlatform.mjs
Allows to use base64 encoded string as image source, e.g.
```javascript
Img : {
src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...',
w: 200,
h: 200
}
```
> Added support for base64 images.

- src/platforms/browser/WebPlatform.mjs
- src/tools/Tools.mjs
- src/tree/Utils.mjs
Followup to https://github.com/rdkcentral/Lightning/pull/227.
This PR adds a guard for the PS4 platform when adding the `crossOrigin` attribute to images, as it causes CORS errors.
> Don't set crossOrigin attribute on images on PS4 platform (#226)

- src/renderer/webgl/shaders/RoundedRectangleShader.mjs
RoundedRectangleShader strokeColor, fillColor and stroke values should be passed as Float32Array to avoid exceptions. #234
> RoundedRectangleShader wrong uniform values

- src/renderer/c2d/C2dTextureTintManager.mjs
I believe we should be calling `clear()` on the tint cache instance rather than the texture directly.
> Fix error when aggressively garbage collecting canvas2d textures (#246)

- devtools/lightning-inspect.js
`data-testid` is a common way to define unique identifier for usage with functional testing tools, such as Suitest, Cypress etc.
With this PR, users will be able to specify the id like so:
```
{
rect: true,
w: 200, h: 200, y: 10, x: 10,
testId: 'login-button'
}
```
Then, in inspector it will be rendered as:
```
<div data-testid="login-button" ... />
```
There is a branch already created with similar functionality [feature/inspector-custom-id](https://github.com/rdkcentral/Lightning/tree/feature/inspector-custom-id), but there is no pull request open and it's already 6 month old. Plus, `data-testid` is arguably cleaner way to do it, as regular `id` might be used for something else in Lightning inspector.
> Add an option to define "data-testid" attribute in inspect mode for functional/e2e testing

- package.json
Systems that scan license IDs expect standard license identifiers from [SPDX](https://spdx.org/licenses/). This also disambiguates between Apache-1.1 and Apache-2.0 and conforms with the [package.json documentation](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license).
> Correctly identify the license of the package

- devtools/lightning-inspect.js
I observed that width and height of the root div for the inspector is retrieved based on a timeout of 1s when inspect scripts is loaded. If the width and / or height of the canvas is modified after this delay, the root div of inspector keep a width and height of 0. As a result, when using Chrome inspector, we do not see the overlay of inspected elements (ie blue rectangle).
Regards
> Inspector, update root div when canvas width update

- src/textures/TextTexture.mjs
- src/textures/TextTextureRendererAdvanced.mjs
Using metadata from fonts with the advanced text renderer users will now be able to set their font baseline ratio.
This enables users to vertically position text accurately within the rasterized text canvas, so that further positioning is accurate.
In addition, the calculation of the height of the text canvas has changed when line height is greater than the font size and the previous calculation of maxLines is not met. 
This is one section I'd appreciate a double-check on. I'm not super familiar with rendering a baseline that is `'ideographic'`. If the font was parsed and the default line height was set from metrics in the fonts, I think it would be ok (the change), but given that the line height defaults to font size when unset, it's possible this change could result in some fonts …
> Improve support for vertical alignment on advanced text renderer.

- src/tree/Stage.mjs
- src/tree/core/CoreContext.mjs
Tested on Tizen 6.0.
The main issue was that when `this._performRender();` was called, it caused flickerings and sometimes the elements even disappeared from the screen.
Since this is something you activate through a specific stage configuration, it looks good to me to merge this into a new version of the Lightning core. We really need this feature/fix because we are targeting these devices and this PR fixes it.
> Added glReadPixels support after rendering

- docs/RuntimeConfig/index.md
- src/platforms/browser/WebPlatform.mjs
- src/tree/Stage.mjs
More reportings of rendering issue similar to #363, this adds a stage option to force `HtmlCanvasElement` as source to prevent having to add exceptions for each individual platform
> Added option to force canvas element as tx source

- docs/RuntimeConfig/index.md
- src/platforms/browser/WebPlatform.mjs
- src/tree/Stage.mjs
When there are no stage updates the Render Engine will stop calling RAF. This will be resumed once there are updates pending.
> Mitigate RAF usage

- src/textures/TextTextureRenderer.mjs
```
innerWidth += (10 - innerWidth);
innerWidth = innerWidth + (10 - innerWidth);
innerWidth = innerWidth + (10 + (-innerWidth));
innerWidth = innerWidth + 10 + (-innerWidth);
innerWidth = 10 // innerWidth and (-innerWidth) cancel each other out
```
> Don't compute a value that is always 10

- docs/RuntimeConfig/index.md
- src/tree/Stage.d.mts
- New 'pauseRafLoopOnIdle' stage option was inadvertently missed from TypeScript defs
- Small updates to other Stage options TSDoc
- Update MD doc on 'forceTxCanvasSource' to emphasize that it effects rendering of any canvas texture (not just text)
> fix: Add missing 'pauseRafLoopOnIdle' stage option type def + small doc updates

- src/platforms/browser/WebPlatform.mjs
> fix: Prevent fatal exception when attempting to render 0x0 canvas texture without forceTxCanvasSource option

- src/platforms/browser/WebPlatform.mjs
- src/tree/Stage.d.mts
- src/tree/Stage.mjs
Functionality of Stage's `drawFrame()` was changed in #402 (Mitigate RAF usage). This is causing grief in our own unit tests as well as unit tests of third party users.
This simple change reverts the original functionality while retaining the new RAF feature.
Here we rename the post-RAF `drawFrame()` method to `renderFrame()`, the name of an existing but verifiably dead method (see below). We then create a new `drawFrame()` which implements its pre-RAF behavior by simply calling `updateFrame()` followed by `renderFrame()`.
The original Stage `renderFrame()` method that is being hijacked here is not used elsewhere in the project (nor the SDK). As for possible third party client uses, this is extremely unlikely given that the `this.ctx.frame` method it calls does not even exist in …
> fix: Revert original functionality of drawFrame()

- docs/TypeScript/Components/TemplateSpecs.md
`TemplateSpec.md` mentions that the developer should use `ImplementsTemplateSpec`. There is a typo here, as Implements should be singular as can be seen [here](https://github.com/rdkcentral/Lightning/blob/1cd88a281a527a3d49f4d0ae082f46a406308944/src/application/Component.d.mts#L224). 
This fixes the issue.
> Fix typo on TemplateSpec.md

- docs/RenderEngine/Textures/Toolbox.md
- docs/Transitions/Methods.md
- docs/RenderEngine/Textures/Toolbox.md
- `Tools.getSvgTexture()` is used to get an SVG texture, not `Tools.createSvg()`
- `createSvg()` just returns an HTMLCanvasElement via a callback method and is used by `getSvgTexture()`
- docs/Transitions/Methods.md
- `transition.start()` requires a targetValue
> Documentation Fixes

- docs/TypeScript/index.md
A user brought to our attention that the `strictNullChecks` TS config must be set to true in order to avoid compiler errors especially when dealing with the `this.tag()` calls. See: https://github.com/rdkcentral/Lightning-SDK/issues/358#issuecomment-1339321527
> Add TypeScript Config Warning

- package.json
Some of the scripts in the MAF-Lightning repo rely on importing the Lightning version from the `package.json`. We might want to revise this in the future, but for now this fixes our issue.
> Expose package.json

- src/textures/TextTexture.mjs
- src/textures/TextTextureRenderer.mjs
- src/textures/TextTextureRendererAdvanced.mjs
- src/textures/TextTextureRendererUtils.mjs
There is an inconsistency in the handling of default fonts depending on if you invoke the TextTexture renderer and call _calculateRenderInfo() directly (as I guess might be done as a pre-render measurement) or if you invoke the TextTexture normally in an attached Lightning Element via the 'text' property. 
This [Lightning playground example](https://lightningjs.io/playground/#N4IgJgpgDhB2mwMYEsIGcQC5QAEA2yA5gBYAusyshAVmgPSID2AThFiGaVGpnQ2LAB0aANYBPKAENEIwZABudfETIUqtBizYAaEMpLlKNemjAj2nbr35DRE6bIVKCBtcbqmROACyCAHIIAzCAAvrpoiMzIUKQY2CB4kgCuSMSCtFigAGbIeGyYCcmp6Ri6TJDsyAC2UCykAAQAglBQ9VnMjFX1AOSCdM1QJd0A3AA6sONMsGgNjDHIjNP1ALz1wDOShBCYawDuOwCcAGwADNr1xDsArN5n9Yh5kswAwox4LDsnAB4nv3+-IRCYyQixm9UkLRW9VgEF2TRaAAo5qQFtMAJTAsCMRBJKpwUiCABGjDAYkEEJg8GexFyYARFOEpE2EEEW1Iz0ksHkkjQCLRGJAukglIQKHQWAA2i …
> Improve text renderer font default

- docs/index.md
Add a link to the TypeDoc API documentation to the bottom of the Lightning Core TOC
> Add API doc link

- src/tree/Element.d.mts
- test-d/Components/Component.test-d.ts
As well as a number accessor, since by default `id` produces a number if it is not overridden.
Fixes #456
> TypeScript: Allow `id` accessor of Component to be overridden by a string accessor

- docs/RenderEngine/Textures/Text.md
- src/textures/TextTextureRenderer.mjs
- src/textures/TextTextureRendererAdvanced.mjs
- src/textures/TextTextureRendererUtils.mjs
- src/textures/TextTextureRendererUtils.test.mjs
This PR enables word wrapping to occur on the zero-width space character `0x200B` ([Unicode Explorer](https://unicode-explorer.com/c/200B), [Wikipedia](https://en.wikipedia.org/wiki/Zero-width_space#:~:text=The%20zero%2Dwidth%20space%20character,%3B%20or%20%E2%80%8B%20.)). This enables developers to programmatically insert these characters in appropriate places for writing systems that do not use space characters to separate words without negatively affecting how the text renders when it is not word wrapped.
This feature has been implemented in both the standard TextTextureRenderer as well as TextTextureRendererAdvanced. However, I noticed that there seem to be unrelated vertical spacing issues with rendering non-Latin script like Chinese that are out of the scope of this feature.
Fixes …
> Implement word wrapping on zero-width breaking spaces

- docs/TypeScript/Components/TypeConfigs.md
- src/application/Component.d.mts
- src/internalTypes.d.mts
- src/tree/Element.d.mts
- test-d/Components/Component-events.test-d.ts
- test-d/Elements/Element-Types.test-d.ts
- test-d/Elements/Element.test-d.ts
Lightning's type system has the concept of Loose Template Specs ([documented here](https://lightningjs.io/docs/#/lightning-core-reference/TypeScript/Components/TemplateSpecs?id=loose-components)) which allow properties and Refs that aren't actually declared in the Template Spec to be specified as if they were `any`. By default all Components that do not specify Template Spec (i.e. use the default Template Spec) use a Loose Template Spec.
Along side the Template Spec we offer another way to make Components more type strong called the [Type Config](https://lightningjs.io/docs/#/lightning-core-reference/TypeScript/Components/TypeConfigs). Unfortunately support for a Loose Type Config was not previously considered and it was brought to my attention by the Lightning UI team that this is making …
> TypeScript: Implement Default Loose Type Configs

- src/renderer/webgl/shaders/DefaultShader.mjs
The conditional is provable `if (true)`.
`pos` starts at 0, and only increments in the for loop below bounded in iterations by `length`.
Therefore, pos can never be greater than length.
> Remove unnecessary conditional

- src/textures/TextTextureRenderer.mjs
- src/textures/TextTextureRendererAdvanced.mjs
- src/textures/TextTextureRendererUtils.mjs
- src/textures/TextTextureRendererUtils.test.mjs
Behavior has been reverted back to pre-2.10.0 behavior while retaining the zero-width space functionality.
- Moves `textWrap()` and `measureText()` methods to TextRendererUtils
- Tests for both with the ability to mock up the C2D context version of measureText()
- All direct context calls to measure text have been changed to use the util method.
- The unit tests for `textWrap()` were originally written to pass for the original implementation prior to adding back the zero-width space functionality (plus a test for that)
- Removes `splitWords()`
- Moves `tokenize()` implementation for advanced renderer to TextRendererUtils w/ unit test
- #488
> TextTextureRenderer: Fix word wrap behavior that regressed in 2.10.0

- package.json
- src/lightning.esm.d.mts
- src/lightning.esm.mjs
- vite.config.js
Also have package.json point directly to the entry point `.d.mts` type definition files. Previously it pointed to `index.d.ts`/`index.js` which as far as I'm aware now isn't used as all as an entry point for the bundler nor is it exported in package.json. I think we might be able to delete those files, though its possible they are used in some way I'm not aware of.
Fixes #480
> Add named export for Lightning in the ESM build

- src/platforms/browser/WebPlatform.mjs
- src/platforms/browser/WebPlatform.test.mjs
This fix solves an issue when the image worker is not being used, so Lightning processes images on the main thread. There is a simple check for `.png` to toggle whether or not the image has an alpha channel. This however gives an issue when a `.PNG` is used. Introduced a simple lowerCase cast to be able to work with both `.png` and `.PNG`.
Additionally added some (quick and dirty) vitest cases to validate the above changes. Resolves: https://github.com/rdkcentral/Lightning/issues/493
> Fix alpha channel detection when using in-process image handling.

- src/tree/Element.d.mts
https://lightningjs.io/docs/#/lightning-core-reference/Templates/Flexbox
Documented as a possibility here to pull a flex item out of the tree.
> Update typings of Element to allow flexItem: false

- src/tree/core/ElementCore.mjs
When elements have the same zIndex they should respect the renderTree. There is a clear attempt at that by using the updateTreeOrder to sort the elements, however the code that triggered the re-sort was removed:
https://github.com/rdkcentral/Lightning/commit/38285e00ef018a23f11e0943507da20f793090db
https://github.com/rdkcentral/Lightning/commit/93b301b5157b73119a967e3c52954a09389da1dc
Since this sort happens only when the tree changes it has a very very low cost, performance wise and is much better than having a wrongly ordered zIndex array.
Other suggestions to fix this bug are very welcome.
> fix: order same zIndex elements by updateTreeOrder

- src/tree/ObjectList.mjs
Adding an element that is already exists in childList through childList.add(Element) and childList.addAt(Element, childlist.length) Leads to throwing an error
It seems the #314  fix introduced this issue.  This PR should resolve #311  and #509 
`  
With this fix the following scenarios are verified 
// Adding existing Element to childList through add()
childList.add(Element)
// Adding existing element to childList through addAt()
childList.addAt(Element, childList.length)
// Set existing element at end of chidList
childList.setAt(Element, childList.length)
// Set new Element at end of childList
childList.setAt(newElement, childList.length)
// This statement should throw Error as new element can't be replaced at non existing index
// Set new Element at existing index location …
> Adding duplicate element by childList.add

- src/tools/Tools.mjs
Currently, SVG txError events are not triggered due to errors not getting captured. This change correctly handles the onerror event, which subsequently triggers the txError correctly.
> Fix SVG txError not triggering

- src/tree/Element.mjs
It looks like there has been (forever) a bug in the elements' `txLoaded` event, over-firing because it incorrectly identifies texture changes.
`this.__core.displayedTextureSource` is a `TextureSource` but was apparently used in the code as if it was a `Texture` (thank you untyped JS).
> Fix texture changed logic

- src/renderer/webgl/shaders/RoundedRectangleShader.mjs
At it's current state, when setting a value for stroke on the RoundedRectangleShader the stroke itself gets clipped incorrectly.
This is more noticiable when you put the radius at half the height (on a square) to make it a circle and then you can see it clipping the top/bottom and left/right of the stroke.
Round:
vs
Rectangle:
vs
> fix: RoundedRectangleShader clipping stroke

- src/textures/TextTexture.mjs
- src/textures/TextTextureRenderer.mjs
Hi ! in our project we have Arabic texts which are displayed correctly by the canvas but the bidirectional texts always have a LTR global context so text blocs are not displayed well when our UI is in RTL.
This change set the canvas context direction to allow the browser to handle properly bidirectional texts.
> feature: TextTexture handle right to left text direction

- CHANGELOG.md
- package-lock.json
- package.json
- scripts/src-to-dist.cjs
- src/textures/TextTexture.mjs
- src/textures/TextTextureRenderer.mjs
- Fixed an issue causing not including TypeScript types in the build. (#527)
- Enhanced handling of bidirectional text in `TextTexture` by setting canvas context direction to correct display of text blocks in RTL configurations. (#526)
- #527 
- #528  
- #526
> Release - v2.13.0

- CHANGELOG.md
- package-lock.json
- package.json
During publish of the package the Typescript definition files weren't properly built.
Ran a new release and tagged it as 2.13.1
> Hotfix - properly publishing typescript types.

- src/tree/TextureManager.mjs
https://github.com/rdkcentral/Lightning/issues/520
> Remove duplicate _cleanupLookupMap call

- src/tree/Stage.mjs
When memory is released, calling `Stage.addMemoryUsage` with a negative `delta`, we should never trigger a `gc`.
Fixes #529
> Fix - Don't GC when releasing memory

- src/textures/TextTextureRendererUtils.mts
Fixes #537
Adding double quote to font names enforces web-fonts, but quotes are only required when the font name includes a space.
> Fix font family normalization

- CHANGELOG.md
- package-lock.json
- package.json
- src/textures/TextTextureRendererUtils.mts
- src/tree/Stage.mjs
- src/tree/TextureManager.mjs
- Fixes limiting behaviour that prevented using other system fonts. (#537)
- Fixes duplicated call for `_cleanupLookupMap()` in the garbage collection function. (#520)
- Fixes the issue causing double freeing of textures due to the garbage collection triggered during releasing memory. (#529)
- #537
- #520 
- #529 
- #532    
- #535 
- #538 
- #539
> Release - v2.13.2

- src/platforms/browser/WebPlatform.mjs
Moving onIdle reset, it wasn't clearing it consistently due to rafloop and start / stop loop sequence.
> fix: Reset onIdle on every RAF subloop

- .github/workflows/pr-validation.yml
- src/textures/TextTextureRendererUtils.test.mjs
- tsconfig.json
Some recent-ish changes broke the (rare) unit tests.
Here's a workflow.
PS: there are visual tests which could also be run, but they are currently failing
> Add Github workflow to validate PRs

- src/platforms/browser/WebPlatform.mjs
- src/platforms/browser/WebPlatform.test.mjs
> Relative URLs in Web Workers
> Web Workers run in a separate thread from the main JavaScript execution context. Because of this, they do not have direct access to the DOM, including the BASE tag or the document's URL. This affects how relative URLs are resolved.
Failure to provide a full URL will cause a global `SyntaxError` error to be raised, which won't result in a texture error.
> Fix: ImageWorker can't load relative URLs

- docs/Animations/Actions.md
- src/animation/AnimationActionSettings.d.mts
- src/animation/AnimationActionSettings.mjs
- src/animation/AnimationActionSettings.test.mjs
As was mentioned in the TS comments, using a String as animation target can't be type-safe.
It is however useful to be able to animate multiple elements as one single animation, so we have modified the selection logic to allow passing a reference directly for the animation.
```javascript
// before (untyped)
actions: [
{ t: 'SomeUnsafeTarget', ...}
]
// after
actions: [
{ t: this.tag('SomeTypeSafeTarget'), ...}
]
```
> Feature - animation by ref

- .github/workflows/playwright.yml
- .gitignore
- package-lock.json
- package.json
- playwright.config.ts
- tests/automation.spec.ts
- tests/event-emitter/test.event-emitter.js
- tests/keyhandler/test.keyhandleLong.js
- tests/keyhandler/test.keyhandler.js
- tests/layout/src/flexToHtml/MismatchCollector.mjs
- tests/layout/test.layout.js
- tests/layout/test.misc.js
- tests/layout/test.relative.js
- tests/layout/test.updates.js
- tests/shaders/test.grayscale.js
- tests/template/test.template.js
- tests/test.html
- tests/textures/test.text.js
- tests/textures/test.textures.js
- vite.config.js
Some Mocha browser tests were present in the repository - however they wouldn't work in their current state:
- HTML page referenced incorrect Lightning runtime,
- Some Flexbox tests would not pass; it may be that Lightning engine diverged a little bit from HTML flexbox which was used as reference. I added a workaround to ignore divergences.
Added an automation script to run those browser tests. 
This required to adjust the Mocha tests because:
- All the Mocha tests were running in a way hard to track with Playwright,
- The tests create many Lightning stages which never stop running, which would be very heavy for CI; now the stages are stopped after the tests end.
Playwright tests now run as part of CI checks.
> Add Playwright browser tests

- src/platforms/browser/WebPlatform.mjs
In some apps, image URLs are generated like this:
```js
export const getImgUrl = (imgPath, width = 185)=> {
return `//image.example.org/t/p/w${width}${imgPath}`
};
```
So we should not expect `://` to be present in all image URLs.
> Image URL validation fix for image worker

- src/tree/core/ElementCore.mjs
- tests/rtl/test.rtl.js
`Element`'s `texture` instance doesn't receive the RTL flag in some scenarios due to the "side-effects optimisation" in `ElementCore`, this causes text alignment to not be automatically mirrored (e.g. `left` alignment becoming `right`).
Note:
- the bug doesn't happen with the classic component templating approach, only when manually creating elements,
- test file was reformatted, the main addition is the new `it("Should propagate flag after attachment"` new last case, plus a few assertions that labels were rendered with the right direction flag.
In this screenshot, before the bug, the "Dynamic attachment" label would remain left-aligned instead of being right aligned with the blue box as we can see here:
> Fix text texture RTL propagation

- src/textures/TextTextureRendererAdvanced.mjs
- tests/rtl/test.rtl.js
Until the text renderers are replaced: mirror alignment in advanced text renderer.
> Fix advanced renderer text alignment mirroring

- package.json
- vite.config.js
Fix npm package is inconsistent between ESM and ES5:
- `dist/lightning.*` was bundling `src/lightning.mjs` instead of `src/index.ts`, which means it was missing some of the exports. This change increases the `min.js` file by about 2Kb.
- require `devtools` was not pointing to the ES5 version which is produced using Vite.
> Fix ES5 package

- package.json
- src/textures/TextTextureRenderer.ts
- src/textures/TextTextureRendererTypes.ts
Improve text renderer's `renderInfo` to return the full lines layout (each line's x and y). The lines layout is just moved into `_calculateRenderInfo` instead of being calculated in the `_draw` method.
This is necessary, when implementing bidirectional (LTR / RTL) text input, to correctly calculate the caret.
> Feature: expose lines layout in renderInfo

- docs/RTL/index.md
- src/textures/bidi.d.mts
- src/textures/bidiTokenizer.ts
- tests/text-rendering.html
- tests/text-rendering.spec.ts
- tests/text-rendering/index.js
The initial implementation of bidirectional text rendering suffers from gaps:
- Generally we aim to follow HTML `auto` behavior,
- However we don't handle “weakly directional” text, e.g. `5 {RTL minutes}` will be considered LTR primary (`5`) followed by RTL text, while `5` is weak and it should inherit the RTL direction,
- We don't support “isolates”, e.g. control characters (`LFI` - left isolate, `RLI` - right isolate, `FSI` - auto isolate, `PDI` - pop isolate) which should be usable to control the direction of the rendering for spans of text. 
The last point is important to correctly render mixed LTR/RTL text, where you want to ensure one general layout (for instance wrapping with a `RLI` isolate) but concatenating labels which could be English or RTL (for instance an English title …
> Add direction detection and isolates

- src/tree/Stage.mjs
- src/tree/core/CoreContext.d.mts
- src/tree/core/ElementCore.d.mts
- src/tree/core/ElementCore.mjs
Fixes #554 - getChildrenByPosition wrong order
Might fix #129 - zIndexedChildren order obsolete when out of bounds
`Stage.getChildrenByPosition(x, y)` collects elements at the (global) `x, y` location, internally calling `ElementCore.collectAtCoord(x, y, children)`
```javascript
getChildrenByPosition(x, y) {
// collector target
const children = [];
// force updating from the root
this.root.core.update();
// collect children recursively
this.root.core.collectAtCoord(x, y, children);
return children;
}
```
Internally, `collectAtCoord` sorts the result using `ElementCore.sortZIndexedChildren`. The issue with this sorting function is that it doesn't just sort by `zIndex`, but also by `core._updateTreeOrder`, but this value can be wrong.
One may think that `this.root.core.update()` would …
> Fix: occasional incorrect tree order in `getChildrenAtPosition`

- package-lock.json
- package.json
- vite.config.js
Fixes #536 - Lightning Core > 2.11.0 Unsupported on older browsers
ESbuild/Rollup doesn't seem to allow Babel do the transpilation to older browsers. This is a regression which I didn't try exactly narrowing.
This PR forces all the JS transformation to be done through Babel - it still is properly minified and the JS size is about the same size (~432Kb for `lightning.es5.min.js`)
> Fix ES5 output by using only Babel in this case
